### ISSUE TITLE
弄一个配置导出 导入的功能吧

### ISSUE THREAD

**Issue by huanx9** [nancy54264/z-player#1]
这样方便操作

**Comment by nbeezander** [comment]
嗯，有考虑。准备加，下个版本

**Comment by huanx9** [comment]
最好不是加密的。 

可以在PC上编辑好txt 格式。然后复制到android上，导入即可。

**Comment by liuxing7954** [comment]
貌似不能用..

**Comment by huanx9** [comment]
催更！！  没有这个功能 手动编辑太累了

**Comment by lj98lj98** [comment]
json也行

**Comment by nbeezander** [comment]
> 催更！！ 没有这个功能 手动编辑太累了

呃。。目前还没空闲时间。方案已经有了。准备做成json格式。

**Comment by nbeezander** [comment]
> 催更！！ 没有这个功能 手动编辑太累了

哥们，，今天我抽时间写了一下，上传了 1.0.2 .久等久等

**Comment by huanx9** [comment]
感谢开发者。其实json能直接导入最好了。。不然要全选复制 粘贴~~ 
吹毛求疵罢了。。现在已经很舒服了。

**Comment by huanx9** [comment]
更新两个BUG 。。

第一个是  json信息导入，不知道在什么情况下就会造成  排序错误。。列表错乱..

第二个是 资源下 好像光有 api接口 有的网站好像并不能加载出来..

**Comment by nbeezander** [comment]
> 更新两个BUG 。。
> 
> 第一个是 json信息导入，不知道在什么情况下就会造成 排序错误。。列表错乱..
> 
> 第二个是 资源下 好像光有 api接口 有的网站好像并不能加载出来..

呃。。。第一个问题，可能是数据异步操作导致的顺序不一致，我试试有没有更好的实现方式，
第二个问题:  是的，目前我这边只实现了httpApis 这一种解析方式，后面可能会保持和hplayer一致。

感谢Issue.
